//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlastairLundy.DotPrimitives.Meta.Internals.Localizations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AlastairLundy.DotPrimitives.Meta.Internals.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Exceptions_PlatformNotSupported_EndOfLifeOperatingSystem {
            get {
                return ResourceManager.GetString("Exceptions.PlatformNotSupported.EndOfLifeOperatingSystem", resourceCulture);
            }
        }
        
        internal static string MonikerTypes_Mono {
            get {
                return ResourceManager.GetString("MonikerTypes.Mono", resourceCulture);
            }
        }
        
        internal static string MonikerTypes_Framework {
            get {
                return ResourceManager.GetString("MonikerTypes.Framework", resourceCulture);
            }
        }
        
        internal static string MonikerTypes_NetCore {
            get {
                return ResourceManager.GetString("MonikerTypes.NetCore", resourceCulture);
            }
        }
        
        internal static string MonikerTypes_Net5Plus {
            get {
                return ResourceManager.GetString("MonikerTypes.Net5Plus", resourceCulture);
            }
        }
        
        internal static string MonikerTypes_Xamarin {
            get {
                return ResourceManager.GetString("MonikerTypes.Xamarin", resourceCulture);
            }
        }
        
        internal static string MonikerTypes_Maui {
            get {
                return ResourceManager.GetString("MonikerTypes.Maui", resourceCulture);
            }
        }
        
        internal static string MonikerTypes_NetCore_Full {
            get {
                return ResourceManager.GetString("MonikerTypes.NetCore.Full", resourceCulture);
            }
        }
        
        internal static string TargetSystem_Android {
            get {
                return ResourceManager.GetString("TargetSystem.Android", resourceCulture);
            }
        }
        
        internal static string TargetSystem_Ios {
            get {
                return ResourceManager.GetString("TargetSystem.Ios", resourceCulture);
            }
        }
        
        internal static string TargetSystem_Windows {
            get {
                return ResourceManager.GetString("TargetSystem.Windows", resourceCulture);
            }
        }
        
        internal static string TargetSystem_Mac {
            get {
                return ResourceManager.GetString("TargetSystem.Mac", resourceCulture);
            }
        }
        
        internal static string TargetSystem_Tizen {
            get {
                return ResourceManager.GetString("TargetSystem.Tizen", resourceCulture);
            }
        }
        
        internal static string TargetSystem_MacCatalyst {
            get {
                return ResourceManager.GetString("TargetSystem.MacCatalyst", resourceCulture);
            }
        }
        
        internal static string TargetSystem_Browser {
            get {
                return ResourceManager.GetString("TargetSystem.Browser", resourceCulture);
            }
        }
        
        internal static string TargetSystem_WatchOs {
            get {
                return ResourceManager.GetString("TargetSystem.WatchOs", resourceCulture);
            }
        }
        
        internal static string TargetSystem_TvOs {
            get {
                return ResourceManager.GetString("TargetSystem.TvOs", resourceCulture);
            }
        }
        
        internal static string TargetSystem_VisionOs {
            get {
                return ResourceManager.GetString("TargetSystem.VisionOs", resourceCulture);
            }
        }
        
        internal static string Exceptions_PlatformNotSupported_LinuxOnly {
            get {
                return ResourceManager.GetString("Exceptions.PlatformNotSupported.LinuxOnly", resourceCulture);
            }
        }
    }
}
