//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlastairLundy.DotPrimitives.Meta.Internals.Localizations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AlastairLundy.DotPrimitives.Meta.Internals.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Attributes_Deprecations_Deprecated_FutureGeneric {
            get {
                return ResourceManager.GetString("Attributes.Deprecations.Deprecated.FutureGeneric", resourceCulture);
            }
        }
        
        internal static string Attributes_Deprecations_Deprecated_FutureSpecific {
            get {
                return ResourceManager.GetString("Attributes.Deprecations.Deprecated.FutureSpecific", resourceCulture);
            }
        }
        
        internal static string Exceptions_PlatformNotSupported_RequiresOs {
            get {
                return ResourceManager.GetString("Exceptions.PlatformNotSupported.RequiresOs", resourceCulture);
            }
        }
        
        internal static string Exceptions_PlatformNotSupported_EndOfLifeOperatingSystem {
            get {
                return ResourceManager.GetString("Exceptions.PlatformNotSupported.EndOfLifeOperatingSystem", resourceCulture);
            }
        }
        
        internal static string Labels_MonikerTypes_Core {
            get {
                return ResourceManager.GetString("Labels.MonikerTypes.Core", resourceCulture);
            }
        }
        
        internal static string Labels_MonikerTypes_Core_Full {
            get {
                return ResourceManager.GetString("Labels.MonikerTypes.Core.Full", resourceCulture);
            }
        }
        
        internal static string Labels_MonikerTypes_Framework {
            get {
                return ResourceManager.GetString("Labels.MonikerTypes.Framework", resourceCulture);
            }
        }
        
        internal static string Labels_MonikerTypes_Maui {
            get {
                return ResourceManager.GetString("Labels.MonikerTypes.Maui", resourceCulture);
            }
        }
        
        internal static string Labels_MonikerTypes_Mono {
            get {
                return ResourceManager.GetString("Labels.MonikerTypes.Mono", resourceCulture);
            }
        }
        
        internal static string Labels_MonikerTypes_NetStandard {
            get {
                return ResourceManager.GetString("Labels.MonikerTypes.NetStandard", resourceCulture);
            }
        }
        
        internal static string Labels_MonikerTypes_Net5Plus {
            get {
                return ResourceManager.GetString("Labels.MonikerTypes.Net5Plus", resourceCulture);
            }
        }
        
        internal static string Labels_MonikerTypes_Xamarin {
            get {
                return ResourceManager.GetString("Labels.MonikerTypes.Xamarin", resourceCulture);
            }
        }
        
        internal static string Labels_TargetSystem_Android {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.Android", resourceCulture);
            }
        }
        
        internal static string Labels_TargetSystem_Browser {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.Browser", resourceCulture);
            }
        }
        
        internal static string Labels_TargetSystem_Ios {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.Ios", resourceCulture);
            }
        }
        
        internal static string Labels_TargetSystem_Mac {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.Mac", resourceCulture);
            }
        }
        
        internal static string Labels_TargetSystem_MacCatalyst {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.MacCatalyst", resourceCulture);
            }
        }
        
        internal static string Labels_TargetSystem_TvOs {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.TvOs", resourceCulture);
            }
        }
        
        internal static string Labels_TargetSystem_VisionOs {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.VisionOs", resourceCulture);
            }
        }
        
        internal static string Labels_TargetSystem_WatchOs {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.WatchOs", resourceCulture);
            }
        }
        
        internal static string Labels_TargetSystem_Windows {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.Windows", resourceCulture);
            }
        }
    }
}
