//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resyslib.Internal.Localizations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resyslib.Internal.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Exceptions_ArgumentConflict_Generic {
            get {
                return ResourceManager.GetString("Exceptions.ArgumentConflict.Generic", resourceCulture);
            }
        }
        
        internal static string Exceptions_ArgumentConflictBuilder_NullArgument {
            get {
                return ResourceManager.GetString("Exceptions.ArgumentConflictBuilder.NullArgument", resourceCulture);
            }
        }
        
        internal static string Errors_Attributes_InvalidValue {
            get {
                return ResourceManager.GetString("Errors.Attributes.InvalidValue", resourceCulture);
            }
        }
        
        internal static string Errors_Attributes_AllowedValues {
            get {
                return ResourceManager.GetString("Errors.Attributes.AllowedValues", resourceCulture);
            }
        }
        
        internal static string Exceptions_ArgumentConflict_CurrentParameter {
            get {
                return ResourceManager.GetString("Exceptions.ArgumentConflict.CurrentParameter", resourceCulture);
            }
        }
        
        internal static string Exceptions_Attributes_NullValue {
            get {
                return ResourceManager.GetString("Exceptions.Attributes.NullValue", resourceCulture);
            }
        }
    }
}
