//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlastairLundy.Resyslib.Internal.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlastairLundy.Resyslib.Internal.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter value provided is not a specifically allowed value. Please see the implementer&apos;s documentation for a list of allowed values..
        /// </summary>
        internal static string Errors_Attributes_AllowedValues {
            get {
                return ResourceManager.GetString("Errors.Attributes.AllowedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter value provided is an invalid value and is not allowed. Please see the implementer&apos;s documentation for invalid values..
        /// </summary>
        internal static string Errors_Attributes_InvalidValue {
            get {
                return ResourceManager.GetString("Errors.Attributes.InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of {arg1} conflicts with the value of the current parameter..
        /// </summary>
        internal static string Exceptions_ArgumentConflict_CurrentParameter {
            get {
                return ResourceManager.GetString("Exceptions.ArgumentConflict.CurrentParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two or more arguments provided are mutually exclusive and cannot both be applied..
        /// </summary>
        internal static string Exceptions_ArgumentConflict_Generic {
            get {
                return ResourceManager.GetString("Exceptions.ArgumentConflict.Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument provided to the ConflictingArgumentBuilder, with name {arg}, was null..
        /// </summary>
        internal static string Exceptions_ArgumentConflictBuilder_NullArgument {
            get {
                return ResourceManager.GetString("Exceptions.ArgumentConflictBuilder.NullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter value provided, with name {arg}, was null..
        /// </summary>
        internal static string Exceptions_Attributes_NullValue {
            get {
                return ResourceManager.GetString("Exceptions.Attributes.NullValue", resourceCulture);
            }
        }
    }
}
