//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlastairLundy.Primitives.Internal {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AlastairLundy.Primitives.Internal.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Labels_Key {
            get {
                return ResourceManager.GetString("Labels.Key", resourceCulture);
            }
        }
        
        internal static string Labels_Value {
            get {
                return ResourceManager.GetString("Labels.Value", resourceCulture);
            }
        }
        
        internal static string Exceptions_ResourcePolicy_CannotSetToNonStartedProcess {
            get {
                return ResourceManager.GetString("Exceptions.ResourcePolicy.CannotSetToNonStartedProcess", resourceCulture);
            }
        }
        
        internal static string Exceptions_ProcessConfiguration_TargetFilePath_Empty {
            get {
                return ResourceManager.GetString("Exceptions.ProcessConfiguration.TargetFilePath.Empty", resourceCulture);
            }
        }
        
        internal static string Labels_ProcessConfiguration_ToString_RequiresAdmin {
            get {
                return ResourceManager.GetString("Labels.ProcessConfiguration.ToString.RequiresAdmin", resourceCulture);
            }
        }
        
        internal static string Labels_ProcessConfiguration_ToString_ShellExecution {
            get {
                return ResourceManager.GetString("Labels.ProcessConfiguration.ToString.ShellExecution", resourceCulture);
            }
        }
        
        internal static string Labels_ProcessConfiguration_ToString_WorkingDirectory {
            get {
                return ResourceManager.GetString("Labels.ProcessConfiguration.ToString.WorkingDirectory", resourceCulture);
            }
        }
    }
}
