//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotPrimitives.Internals.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotPrimitives.Internals.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature or element is deprecated and may be removed in a future version..
        /// </summary>
        internal static string Attributes_Deprecations_Deprecated_FutureGeneric {
            get {
                return ResourceManager.GetString("Attributes.Deprecations.Deprecated.FutureGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature or element is deprecated and may be removed in version {x}..
        /// </summary>
        internal static string Attributes_Deprecations_Deprecated_FutureSpecific {
            get {
                return ResourceManager.GetString("Attributes.Deprecations.Deprecated.FutureSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{directory}&apos; could not be found or does not exist..
        /// </summary>
        internal static string Exceptions_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Exceptions.DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{file}&apos; could not be found or does not exist..
        /// </summary>
        internal static string Exceptions_FileNotFound {
            get {
                return ResourceManager.GetString("Exceptions.FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Invalid Unix Numeric file permission notation of {x} was provided..
        /// </summary>
        internal static string Exceptions_Permissions_Unix_InvalidNumericNotation {
            get {
                return ResourceManager.GetString("Exceptions.Permissions.Unix.InvalidNumericNotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Invalid Unix Symbolic file permission notation of {x} was provided..
        /// </summary>
        internal static string Exceptions_Permissions_Unix_InvalidSymbolicNotation {
            get {
                return ResourceManager.GetString("Exceptions.Permissions.Unix.InvalidSymbolicNotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Operating System is not supported because it has reached End Of Life status and is not supported by its developer..
        /// </summary>
        internal static string Exceptions_PlatformNotSupported_EndOfLifeOperatingSystem {
            get {
                return ResourceManager.GetString("Exceptions.PlatformNotSupported.EndOfLifeOperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not supported on the currently running platform. This feature requires {targetOs}..
        /// </summary>
        internal static string Exceptions_PlatformNotSupported_RequiresOs {
            get {
                return ResourceManager.GetString("Exceptions.PlatformNotSupported.RequiresOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Process Configuration&apos;s Target File Path cannot be null or empty..
        /// </summary>
        internal static string Exceptions_ProcessConfiguration_TargetFilePath_Empty {
            get {
                return ResourceManager.GetString("Exceptions.ProcessConfiguration.TargetFilePath.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set Resource Policy to a Process that has not already been started..
        /// </summary>
        internal static string Exceptions_ResourcePolicy_CannotSetToNonStartedProcess {
            get {
                return ResourceManager.GetString("Exceptions.ResourcePolicy.CannotSetToNonStartedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string Labels_Key {
            get {
                return ResourceManager.GetString("Labels.Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin.
        /// </summary>
        internal static string Labels_MonikerTypes_Xamarin {
            get {
                return ResourceManager.GetString("Labels.MonikerTypes.Xamarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to android.
        /// </summary>
        internal static string Labels_TargetSystem_Android {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browser.
        /// </summary>
        internal static string Labels_TargetSystem_Browser {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ios.
        /// </summary>
        internal static string Labels_TargetSystem_Ios {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.Ios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mac.
        /// </summary>
        internal static string Labels_TargetSystem_Mac {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.Mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maccatalyst.
        /// </summary>
        internal static string Labels_TargetSystem_MacCatalyst {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.MacCatalyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tvos.
        /// </summary>
        internal static string Labels_TargetSystem_TvOs {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.TvOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visionos.
        /// </summary>
        internal static string Labels_TargetSystem_VisionOs {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.VisionOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watchos.
        /// </summary>
        internal static string Labels_TargetSystem_WatchOs {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.WatchOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to windows.
        /// </summary>
        internal static string Labels_TargetSystem_Windows {
            get {
                return ResourceManager.GetString("Labels.TargetSystem.Windows", resourceCulture);
            }
        }
    }
}
